backend:
  name: github
  repo: muxunorg/mxfree.ao-x.ac.cn
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://mxfree.ao-x.ac.cn
  base_url: https://mxfree.ao-x.ac.cn
  auth_endpoint: /api/auth
media_folder: public/img
public_folder: /img
collections:
  - label: '页面'
    name: 'pages' 
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: "首页"
        name: "index"
        file: "/index.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
        files:
      - label: "下载-正式版"
        name: "download"
        file: "/download.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "下载-测试版"
        name: "beta"
        file: "/beta.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "捐助"
        name: "donate"
        file: "/donate.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }